import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {orderedPeople, familyEdges, jurisdictionChain, inYears, project, arcPath, routeSegments, validateBoundaries, boundaryPath, clampView} from '../assets/context-model.js';
const geo=JSON.parse(readFileSync(new URL('../data/geography.json',import.meta.url),'utf8'));
const catalog=JSON.parse(readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));
const ids=['subject','father','envoy','friend','scholar'];
test('active people are adjacent after the pinned subject',()=>assert.deepEqual(orderedPeople(ids,['friend','scholar'],'subject',ids),['subject','friend','scholar','father','envoy']));
test('relative ordering remains stable within each group',()=>assert.deepEqual(orderedPeople(ids,['friend','envoy'],'subject',['subject','friend','scholar','envoy','father']),['subject','friend','envoy','scholar','father']));
test('changing group does not mutate source order',()=>{const copy=[...ids];orderedPeople(ids,['friend'],'subject',ids);assert.deepEqual(ids,copy);});
test('no duplicate or nonexistent pinned people',()=>assert.deepEqual(orderedPeople(['a','a','b'],['b'],'c',['gone','a']),['b','a']));
test('child-of maps to parent-to-child, not the other way around',()=>{const e=familyEdges(catalog.relations,['person-zeng-jize','person-zeng-guofan']);assert.equal(e[0].parent,'person-zeng-guofan');assert.equal(e[0].child,'person-zeng-jize');assert.ok(e[0].evidence.length);});
test('no invented kin edges for unrelated people',()=>assert.deepEqual(familyEdges(catalog.relations,['person-macartney','person-guo-songtao']),[]));
test('rejected and self relationships do not draw',()=>assert.deepEqual(familyEdges([{predicate:'child-of',subject:'a',object:'a'},{predicate:'child-of',subject:'a',object:'b',status:'rejected'}],['a','b']),[]));
test('county chain has actual historic prefecture and province',()=>assert.deepEqual(jurisdictionChain(geo.jurisdictions,'xiangxiang',1878).map(j=>j.label),['湖南省','長沙府','湘鄉縣']));
test('Shanghai is not its modern province-level municipality',()=>assert.deepEqual(jurisdictionChain(geo.jurisdictions,'shanghai',1886).map(j=>j.label),['江蘇省','松江府','上海縣']));
test('Peking is not assigned to an arbitrary county',()=>assert.equal(geo.placeContexts.find(c=>c.place==='place-peking').jurisdiction,'shuntian'));
test('hierarchy is not extrapolated outside its documented pilot coverage',()=>assert.deepEqual(jurisdictionChain(geo.jurisdictions,'xiangxiang',1800),[]));
test('unknown jurisdictions remain unknown',()=>assert.deepEqual(jurisdictionChain(geo.jurisdictions,'missing',1880),[]));
test('cyclic hierarchy is rejected',()=>assert.throws(()=>jurisdictionChain([{id:'a',parent:'b',coverage:{start:1,end:9}},{id:'b',parent:'a',coverage:{start:1,end:9}}],'a',2),/Cyclic/));
test('range endpoints are inclusive',()=>{assert.ok(inYears({start:1839,end:1890},1890));assert.equal(inYears({start:1839,end:1890},1891),false);});
const options={person:'person-zeng-jize',witness:'eccp',passage:'eccp-04',year:1879,scope:'all'};
test('three explicitly separate journeys yield four arcs',()=>assert.equal(routeSegments(geo.journeys,options).length,4));
test('passage filter selects only the relevant journey',()=>assert.equal(routeSegments(geo.journeys,{...options,scope:'passage'}).length,2));
test('year filter hides later destinations',()=>assert.equal(routeSegments(geo.journeys,{...options,scope:'year',year:1878}).length,0));
test('year filter retains known completed legs',()=>assert.equal(routeSegments(geo.journeys,{...options,scope:'year',year:1879}).length,2));
test('no borrowing the main subject’s travel for another person',()=>assert.deepEqual(routeSegments(geo.journeys,{...options,person:'person-zeng-guofan'}),[]));
test('no passing ECCP assertions off as QSG',()=>assert.deepEqual(routeSegments(geo.journeys,{...options,witness:'qsg'}),[]));
test('explicit gaps never become routes',()=>{const j=structuredClone(geo.journeys);j[0].stops[1].breakBefore=true;assert.equal(routeSegments(j,options).length,3);});
test('no interpolated city coordinates',()=>assert.equal(catalog.entities.find(p=>p.id==='place-xiangxiang').point,null));
test('arc coordinates start and finish on the documented endpoints',()=>{assert.deepEqual(project([0,0]),[20,75]);assert.equal(arcPath([0,0],[0,0]),'');const p=arcPath([0,0],[100,40]);assert.ok(p.startsWith('M20,75 '));assert.ok(p.endsWith(' 120,35'));});
// Clearly synthetic geometry, used only for validation, never added to the historical corpus.
const feature=()=>({type:'Feature',properties:{jurisdictionId:'xiangxiang',level:'county',startYear:1870,endYear:1890,source:'https://example.org/synthetic-fixture',license:'CC0-1.0',attribution:'Synthetic test fixture'},geometry:{type:'Polygon',coordinates:[[[110,27],[111,27],[111,28],[110,27]]]}});
const fc=f=>({type:'FeatureCollection',features:f});
test('no fabricated historical boundary is bundled',()=>assert.deepEqual(geo.boundaries,fc([])));
test('valid local boundaries retain metadata',()=>assert.equal(validateBoundaries(fc([feature()]),geo.jurisdictions)[0].properties.attribution,'Synthetic test fixture'));
test('boundary source must be inert HTTP(S)',()=>{const f=feature();f.properties.source='javascript:alert(1)';assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/Unsafe/);});
test('boundary cannot invent a jurisdiction',()=>{const f=feature();f.properties.jurisdictionId='missing';assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/known jurisdiction/);});
test('boundary must have a dated interval',()=>{const f=feature();delete f.properties.startYear;assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/startYear/);});
test('boundary must carry attribution and license',()=>{const f=feature();delete f.properties.license;assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/license/);});
test('unclosed polygon is rejected',()=>{const f=feature();f.geometry.coordinates[0][3]=[110,29];assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/unclosed/);});
test('nonfinite and out-of-world coordinates rejected',()=>{for(const x of [Infinity,NaN,190]){const f=feature();f.geometry.coordinates[0][1][0]=x;assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/Invalid/);}});
test('empty polygons rejected',()=>{const f=feature();f.geometry.coordinates=[];assert.throws(()=>validateBoundaries(fc([f]),geo.jurisdictions),/Empty/);});
test('duplicate intervals rejected',()=>assert.throws(()=>validateBoundaries(fc([feature(),feature()]),geo.jurisdictions),/Duplicate/));
test('polygons retain holes',()=>{const f=feature();f.geometry.coordinates.push([[110,27],[110.1,27],[110.1,27.1],[110,27]]);assert.equal((boundaryPath(f.geometry).match(/Z/g)||[]).length,2);});
test('map camera has bounded overscroll and county-scale zoom',()=>assert.deepEqual(clampView([-10,100,200,.1]),[-10,91.9,170,.1]));
test('every journey stop has dated source evidence and an existing place',()=>{for(const j of geo.journeys){assert.equal(j.status,'agent-proposed');const src=catalog.sources.find(s=>s.id===j.witness);const text=readFileSync(new URL('../'+src.text,import.meta.url),'utf8');assert.ok(text.includes(`id="${j.passage}"`));let previous='';for(const s of j.stops){assert.ok(catalog.entities.some(e=>e.id===s.place&&e.type==='place'));assert.match(s.date,/^\d{4}-\d{2}-\d{2}$/);assert.ok(s.date>=previous);previous=s.date;assert.ok(s.original);assert.ok(['arrival','departure'].includes(s.kind));}}});
test('every hierarchy record cites an existing source and parent',()=>{for(const j of geo.jurisdictions){assert.ok(geo.sources[j.source]?.url);assert.ok(j.locator);if(j.parent)assert.ok(geo.jurisdictions.some(p=>p.id===j.parent));assert.ok(jurisdictionChain(geo.jurisdictions,j.id,1878).length);}});
