import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {escapeHTML,safeURL,contextFor,validateProposal,punctuationInsensitive,yearLabel} from '../assets/core.js';
const c=JSON.parse(readFileSync(new URL('../data/catalog.json',import.meta.url),'utf8'));
test('HTML escaping',()=>assert.equal(escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('unsafe URL rejected',()=>assert.equal(safeURL('javascript:alert(1)'),null));
test('https URL retained',()=>assert.equal(safeURL('https://ctext.org/'),'https://ctext.org/'));
test('punctuation comparison does not remove Han characters',()=>assert.equal(punctuationInsensitive('甲，乙。'),'甲乙'));
test('diacritics remain significant',()=>assert.notEqual(punctuationInsensitive('Tseng'),punctuationInsensitive('Tsêng')));
test('context uses the current witness only',()=>assert.equal(contextFor(c,'qsg','eccp-03').events.length,0));
test('related people include subject',()=>assert.ok(contextFor(c,'eccp','eccp-03').entityIds.includes('person-zeng-jize')));
test('date display is year scale',()=>assert.equal(yearLabel({start:1878,end:1879}),'1878–1879'));
const proposal=()=>({schemaVersion:1,id:'test',operation:'relink-mention',witness:'eccp',mention:c.mentions[0].id,baseSha256:c.sources[0].sha256,before:c.mentions[0].entity,after:'person-zeng-guofan',reason:'Synthetic test, not a historical judgment.',status:'proposed'});
test('valid correction proposal',()=>assert.equal(validateProposal(proposal(),c).id,'test'));
test('stale correction rejected',()=>assert.throws(()=>validateProposal({...proposal(),baseSha256:'old'},c),/Stale/));
test('unknown person rejected',()=>assert.throws(()=>validateProposal({...proposal(),after:'invented'},c),/Unknown/));
test('no-op rejected',()=>assert.throws(()=>validateProposal({...proposal(),after:proposal().before},c),/unchanged/));
test('review reason required',()=>assert.throws(()=>validateProposal({...proposal(),reason:''},c),/Explain/));
