import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {identityName,nameDetails,periodContains,nameAtYear,paragraphAnchor,sourceNameGroups,sourceDate} from '../assets/name-history.js';
import {personHeading} from '../assets/person-display.js';
const person={id:'person-test',name:{surname:'測',given:'試',bracket:{kind:'county',label:'甲縣'},zi:[{value:'甲字'}],hao:[{value:'乙號'}]},life:{}};
const history={people:{'person-test':{names:[{id:'earlier',surname:'另',given:'名',from:1800,to:1820}],titles:[{id:'t1',label:'某總督',from:1820,to:1830,kind:'office',priority:1},{id:'t2',label:'某大學士',from:1830,to:1841,kind:'office',defaultDisplay:true,priority:1}]}}};
test('headings have a principal name plus smaller separately typed aliases, no parentheses',()=>{const s=personHeading(person);assert.match(s,/>\[甲縣\] 測試<\/h1>/);assert.match(s,/person-name-details/);assert.match(s,/字<\/span>甲字/);assert.match(s,/號<\/span>乙號/);assert(!s.includes('（'));});
test('clan is only a display qualifier',()=>{assert.equal(identityName({...person,name:{given:'某人',bracket:{kind:'clan',label:'完顏'}}}),'[完顏] 某人');});
test('title changes at the documented exclusive boundary',()=>{assert.equal(nameAtYear(person,1829,history).label,'某總督 測試');assert.equal(nameAtYear(person,1830,history).label,'某大學士 測試');});
test('earlier personal names are selected independently of titles',()=>assert.equal(nameAtYear(person,1810,history).label,'另名'));
test('future offices are not applied to earlier years',()=>assert.equal(nameAtYear(person,1819,history).title,''));
test('undated reading uses the explicit default, not the last array element',()=>assert.equal(nameAtYear(person,null,history).label,'某大學士 測試'));
test('unknown start date never implies unbounded historic usage',()=>assert(!periodContains({from:null,to:null},1800)));
test('open ended known usage is permitted',()=>assert(periodContains({from:1800,to:null},1900)));
test('equally preferred conflicting titles remain unresolved',()=>{const h=structuredClone(history);h.people['person-test'].titles.push({id:'other',label:'另一官',kind:'office',from:1820,to:1830,priority:1});assert.equal(nameAtYear(person,1825,h).title,'');});
test('posthumous titles require explicit primary-name selection',()=>{const h={people:{'person-test':{titles:[{id:'post',label:'某祖',kind:'temple',from:1850,to:null}]}}};assert.equal(nameAtYear(person,1860,h).title,'');h.people['person-test'].titles[0].primaryPosthumous=true;assert.equal(nameAtYear(person,1860,h).title,'某祖');});
test('no arbitrary first-event choice for multiple years',()=>{assert.equal(paragraphAnchor({events:[{time:{start:1800,end:1800}},{time:{start:1801,end:1801}}]},'s','p',{}),null);});
test('explicit paragraph anchor is reproducible',()=>{const h={paragraphAnchors:[{witness:'s',passage:'p',year:1850,status:'proposed'}]};assert.equal(paragraphAnchor({},'s','p',h).year,1850);});
test('undated paragraphs never retain a purported event anchor',()=>assert.equal(paragraphAnchor({events:[]},'s','p',{}),null));
test('source dates do not reuse retrieval dates or event years',()=>{assert.equal(sourceDate({id:'s',retrieved:'2026-09-09',work:'w'},{}).kind,'unresolved');});
test('source-name groups keep exact forms and distinct occurrences',()=>{const c={sources:[{id:'s',work:'w'}],mentions:[{id:'a',entity:'person-test',witness:'s',passage:'p1',quote:'某號'},{id:'b',entity:'person-test',witness:'s',passage:'p2',quote:'某號'},{id:'c',entity:'person-other',witness:'s',passage:'p2',quote:'某號'}]};const g=sourceNameGroups(c,'person-test',{});assert.equal(g[0].forms.get('某號').length,2);});
test('changing projected names does not mutate source or profile data',()=>{const before=JSON.stringify([person,history]);nameAtYear(person,1825,history);assert.equal(JSON.stringify([person,history]),before);});
test('real pilot retains zi/hao classification disagreement',()=>{const h=JSON.parse(fs.readFileSync(new URL('../data/name-history.json',import.meta.url)));const a=h.people['person-zeng-guofan'].attestations;assert.deepEqual(a.map(x=>x.kind),['zi','hao']);assert(a.every(x=>x.value==='滌生'));});
